import React from 'react';
import { useForm } from 'react-hook-form';
import { yupResolver } from '@hookform/resolvers/yup';
import * as yup from 'yup';
import { withAuth } from '@components/withAuth.jsx';
import { api } from '@services/apiService.js';
const schema = yup.object({ tradeRef: yup.string().matches(/^[A-Z]{3}-\d{8}-\d{4}$/, 'Use AAA-YYYYMMDD-NNNN').required('Trade ref is required'), instrumentId: yup.number().integer().positive().required('Instrument ID is required'), counterpartyId: yup.number().integer().positive().required('Counterparty ID is required'), assetClass: yup.string().oneOf(['EQUITY', 'FX', 'BOND', 'DERIVATIVE']).required('Asset class is required'), side: yup.string().oneOf(['BUY', 'SELL']).required('Side is required'), quantity: yup.number().positive().required('Quantity is required'), price: yup.number().min(0).required('Price is required'), tradeDate: yup.date().max(new Date(), 'Trade date cannot be in the future').required('Trade date is required') });
const FieldError = ({ error }) => error ? <p className="form-error">{error.message}</p> : null;
function AddTrade() {
  const { register, handleSubmit, formState: { errors, isSubmitting }, reset, setError } = useForm({ resolver: yupResolver(schema) });
  async function onSubmit(values) { try { await api.createTrade(values); reset(); } catch (error) { setError('root', { message: error.message }); } }
  return <section><h2>Add trade</h2><form onSubmit={handleSubmit(onSubmit)} className="trade-form"><label>Trade ref<input {...register('tradeRef')} placeholder="EQU-20260603-0001" /></label><FieldError error={errors.tradeRef} /><label>Instrument ID<input type="number" {...register('instrumentId')} /></label><FieldError error={errors.instrumentId} /><label>Counterparty ID<input type="number" {...register('counterpartyId')} /></label><FieldError error={errors.counterpartyId} /><label>Asset class<select {...register('assetClass')}><option value="">Select</option><option>EQUITY</option><option>FX</option><option>BOND</option><option>DERIVATIVE</option></select></label><FieldError error={errors.assetClass} /><label>Side<select {...register('side')}><option value="">Select</option><option>BUY</option><option>SELL</option></select></label><FieldError error={errors.side} /><label>Quantity<input type="number" step="any" {...register('quantity')} /></label><FieldError error={errors.quantity} /><label>Price<input type="number" min="0" step="any" {...register('price')} /></label><FieldError error={errors.price} /><label>Trade date<input type="date" {...register('tradeDate')} /></label><FieldError error={errors.tradeDate} />{errors.root && <p className="form-error" role="alert">{errors.root.message}</p>}<button disabled={isSubmitting} type="submit">Submit</button></form></section>;
}
export default withAuth(AddTrade);
